import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "./component/Header"; 
import VantaBackground from "./component/VantaBackground";
import ScrollToTopButton from "./component/scrollToTop";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
          
        
      > 
      <Header />
        <VantaBackground/>
          
        
        <section id="about" className="h-screen flex items-center justify-center bg-gray-100">
          <h2 className="text-4xl font-bold">About</h2>
        </section>

        <section id="skills" className="h-screen flex items-center justify-center bg-white">
          <h2 className="text-4xl font-bold">Skills</h2>
        </section>

        <section id="projects" className="h-screen flex items-center justify-center bg-gray-100">
          <h2 className="text-4xl font-bold">Projects</h2>
        </section>

        <section id="contact" className="h-screen flex items-center justify-center bg-white">
          <h2 className="text-4xl font-bold">Contact Me</h2>
        </section>
        {children}
        <ScrollToTopButton />
      </body>
    </html>
  );
}
